SWIDEA_SITE/ideas/urls.py
from django.urls import path
from .views import *

app_name = 'ideas'

urlpatterns = [
    path('', idea_list, name='idea_list'),
    path('create', idea_create, name='idea_create'),   
    path('<int:pk>', idea_detail, name='idea_detail'),
    path('<int:pk>/update', idea_update, name='idea_update'),
    path('<int:pk>/delete', idea_delete, name='idea_delete'),
    path('devtools/', tool_list, name='tool_list'),
    path('devtools/create', tool_create, name='tool_create'),
    path('devtools/<int:pk>', tool_detail, name='tool_detail'),
    path('devtools/<int:pk>/update', tool_update, name='tool_update'),
    path('devtools/<int:pk>/delete', tool_delete, name='tool_delete'),
    path('<int:pk>/toggle_star', toggle_star, name='toggle_star'),
    path('<int:pk>/change_interest', change_interest, name='change_interest'),
   
]

SWIDEA_SITE/ideas/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class DevTool(models.Model):
    name = models.CharField(max_length=255, default='')
    kind = models.CharField(max_length=255, default='')
    context = models.TextField(default='')

    def __str__(self):
        return self.name

class Idea(models.Model):
    title = models.CharField(max_length=255, default='')
    image=models.ImageField(upload_to='images/', default='')
    content = models.TextField(default='')
    interest = models.IntegerField(default=0)
    devtool = models.ForeignKey(DevTool, on_delete=models.CASCADE, default='')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    
class IdeaImage(models.Model):
    idea = models.ForeignKey(Idea, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/')

    def __str__(self):
        return f"Image for {self.idea.title}"
    

class IdeaStar(models.Model):
    # user = models.ForeignKey(User, on_delete=models.CASCADE)
    idea = models.ForeignKey(Idea, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    # def __str__(self):
    #     return f"{self.user.username} likes {self.idea.title}"
    

SWIDEA_SITE/ideas/forms.py
from django import forms
from .models import Idea, DevTool


class IdeaForm(forms.ModelForm):
    class Meta:
        model = Idea
        fields = ['title', 'content', 'interest', 'devtool']



class DevToolForm(forms.ModelForm):
  class Meta():
    model = DevTool
    fields = ['name', 'kind', 'context']

  

SWIDEA_SITE/ideas/views.py
from django.shortcuts import render, redirect
from .models import Idea, DevTool, IdeaStar, IdeaImage
from .forms import IdeaForm, DevToolForm
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.db.models import Count


def idea_list(request):
    sort = request.GET.get('sort', '')
    ideas = Idea.objects.all()

    if sort == 'starred':
        ideas = ideas.annotate(num_stars=Count('ideastar')).order_by('-num_stars')
    if sort == 'name':
        ideas = ideas.order_by('title')
    elif sort == 'created':
        ideas = ideas.order_by('created_at')
    elif sort == 'latest':
        ideas = ideas.order_by('-updated_at')

    starred_ideas = []
    # if request.user.is_authenticated:
    #     starred_ideas = IdeaStar.objects.filter(user=request.user).values_list('idea_id', flat=True)

    ctx = {
        'ideas': ideas,
        'starred_ideas': starred_ideas
    }
    return render(request, 'idea_list.html', ctx)


def idea_create(request):
    if request.method == "POST":
        form = IdeaForm(request.POST)
        
        if form.is_valid():
            # Create Idea object
            idea = form.save(commit=False)  # Commit=False to prevent saving to DB yet
            image = request.FILES.get('image')
            if image:
                idea.image = image 
            idea.save()      
            
            return redirect("ideas:idea_detail", pk=idea.pk)
    else:
        form = IdeaForm()
       

    context = {
        'form': form,
       
    }
    return render(request, 'idea_create.html', context)


def idea_detail(request, pk):
   idea=Idea.objects.get(id=pk)
   
   ctx = {'idea':idea}
   return render(request, 'idea_detail.html', ctx)

def idea_delete(req,pk):
  Idea.objects.get(id=pk).delete()
  return redirect('ideas:idea_list')


def idea_update(request, pk):
    idea = Idea.objects.get(pk=pk)

    if request.method == "POST":
        form = IdeaForm(request.POST, instance=idea)
       
        if form.is_valid():
            form.save()
           
            return redirect("ideas:idea_detail", pk=pk)
    else:
        form = IdeaForm(instance=idea)
       
    ctx = {
        'form': form,
 
        'idea': idea,
    }
    return render(request, 'idea_update.html', ctx)
#devtools----------------------------------------------

def tool_list(req):
    tools=DevTool.objects.all()
    ctx={
        'tools':tools
    }
    return render(req, 'tool_list.html', ctx)

def tool_create(req):
  if req.method == "GET":
    form = DevToolForm()
    ctx = {'form':form}
    return render(req, 'tool_create.html',ctx)
  form = DevToolForm(req.POST, req.FILES)
  if form.is_valid():
    tool=form.save()
  return redirect("ideas:tool_detail", pk=tool.pk)

def tool_detail(request, pk):
   tool=DevTool.objects.get(id=pk)
   ideas = Idea.objects.filter(devtool=tool)
   context={
      "tool":tool,
      "ideas": ideas
   }
   return render(request, 'tool_detail.html', context)

def tool_delete(req,pk):
  DevTool.objects.get(id=pk).delete()
  return redirect('ideas:tool_list')

def tool_update(req,pk):
  tool = DevTool.objects.get(id=pk)
  if req.method == "GET":
    form = DevToolForm(instance=tool)
    ctx = {'form' : form, 'pk':pk}
    return render(req,'tool_update.html',ctx)
  
  form = DevToolForm(req.POST, req.FILES, instance=tool)
  if form.is_valid():
    form.save()
  return redirect("ideas:tool_detail", pk)


from django.http import JsonResponse

@require_POST

def toggle_star(request, pk):
    idea = Idea.objects.get(id=pk)
    star, created = IdeaStar.objects.get_or_create(idea=idea)
    if not created:
        star.delete()
        starred = False
    else:
        starred = True
    return JsonResponse({'starred': starred})

@require_POST
def change_interest(request, pk):
    idea = Idea.objects.get(id=pk)
    action = request.POST.get('action')
    if action == 'increase':
        idea.interest += 1
    elif action == 'decrease':
        idea.interest -= 1
        if idea.interest < 0:
            idea.interest = 0
    idea.save()
    return JsonResponse({'interest': idea.interest})

SWIDEA_SITE/ideas/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <link href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css" rel="stylesheet">
    <title>{% block title %}{% endblock %}</title>
    <script src="{% static 'js/scripts.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <meta name="csrf_token" content="{{ csrf_token }}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script type="text/javascript" src="/static/js/scripts.js"></script>
</head>
<body>
    <nav class="header">
        <ul class="header-ul">
            <li><a href="/">My SW Idea Manage</a></li>
            <li><a href="/">Ideas list</a></li>
            <li><a href="/create">Ideas create</a></li>
            <li><a href="/devtools">DevTools list</a></li>
            <li><a href="/devtools/create">DevTools create</a></li>
        </ul>
    </nav>
    <div class="content-container">
        <div class="content">
            <div class="row">
                {% block content %}
                
                {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

SWIDEA_SITE/ideas/templates/idea_create.html
{% extends 'base.html' %}

{% block content %}
<h2>아이디어 생성</h2>
 <form
    action="{% url 'ideas:idea_create' %}"
    method="post"
    enctype="multipart/form-data">
    {%csrf_token%}{{ form.as_p }}
    <label for="image">이미지:</label>
    <input type="file" name="image" multiple>
    <button class="btn btn-success">등록하기</button>
  </form>
{% endblock %}

SWIDEA_SITE/ideas/templates/idea_detail.html
{% extends 'base.html' %}

{% block content %}
<h2>아이디어 디테일</h2>


<div class="idea_detail_content">
    <div class="idea_detail_left">
        <div class="image_content">
            {% if idea.image %}
                <img src="{{ idea.image.url }}" alt=" idea thumbnail">
            {% endif %}
            <div class="star">
                <button class="star-btn" data-id="{{ idea.id }}">
                    {% if idea.id in starred_ideas %}
                    <i class="ri-star-fill"></i>
                    {% else %}
                    <i class="ri-star-line"></i>
                    {% endif %}
                </button>
            </div>
        </div>
    </div>
    <div class="idea_detail_right">
        <p>제목|{{ idea.title }}</p>
        <p>관심도|{{ idea.interest }}</p>
        <p>예상 개발툴|<a href="{% url 'ideas:tool_detail' pk=idea.devtool.id %}">{{ idea.devtool }}</a>
        <p>설명|{{ idea.content }}</p>
    </div>
</div>
<div class="idea_detail_btn">
    <form action="/{{idea.id}}/delete" method="post" class="delete-btn">
        {% csrf_token %}
        <input id="input6" type="submit" value="Delete">
    </form>
    
    <button>
        <a href="/{{idea.id}}/update" class="plus">
            <i class="ri-edit-2-line"></i>
            <p>Edit</p>
        </a>
    </button>
    <button>
        <a href="/" class="plus">
            <i class="ri-edit-2-line"></i>
            <p>목록</p>
        </a>
    </button>
</div>

{% endblock %}

SWIDEA_SITE/ideas/templates/idea_list.html
{% extends 'base.html' %}

{% block content %}

<div class="a_row">
    <div class="a_link">
        <a href="?sort=starred" class="">찜하기순</a>
        <a href="?sort=name" class="">이름순</a>
        <a href="?sort=created" class="">등록순</a>
        <a href="?sort=latest" class="">최신순</a>
    </div>
    <div>
        {% for idea in ideas %}
        <div class="col-md-8">
            <div class="image_content">
                {% if idea.image %}
                    <img src="{{ idea.image.url }}" alt=" idea thumbnail">
                {% endif %}
                <div class="star">
                    <button class="star-btn" data-id="{{ idea.id }}">
                        {% if idea.id in starred_ideas %}
                        <i class="ri-star-fill"></i>
                        {% else %}
                        <i class="ri-star-line"></i>
                        {% endif %}
                    </button>
                </div>
            </div>
            <div class="col-content">
                <a href="/{{idea.id}}" class="title">{{idea.title}}<i class="ri-navigation-fill"></i> {{ review.title }}</a>
                <div class="col-content-2">
                    <div class="col-space">
    
                        <div class="interest_content">
                            <p>관심도:</p>
                            <button class="interest-btn" data-id="{{ idea.id }}" data-action="increase">+</button>
                            <span id="interest-{{ idea.id }}">{{ idea.interest }}</span>
                            <button class="interest-btn" data-id="{{ idea.id }}" data-action="decrease">-</button>
                        </div>
                        <div>
                            <p>개발툴|{{ idea.devtool }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

{% endblock %}

SWIDEA_SITE/ideas/templates/idea_update.html
{% extends 'base.html' %}

{% block content %}
<h2>아이디어 수정</h2>

<form method="POST" action="{% url 'ideas:idea_update' pk=idea.pk %}" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  {% if idea.image %}
  <p>현재 이미지:</p>
  <img src="{{ idea.image.url}}" alt="Current Image" style="max-width: 300px;">
  {% endif %}

  <!-- Allow to update image -->
  <label for="image">이미지 업데이트:</label>
  <input type="file" name="image">
  
  <button type="submit">Update Idea</button>
</form>

{% endblock %}

SWIDEA_SITE/ideas/templates/tool_create.html
{% extends 'base.html' %}

{% block content %}
<h2>개발툴 등록</h2>
<form
    action="{% url 'ideas:tool_create' %}"
    method="post"
    enctype="multipart/form-data">
    {%csrf_token%} {{form.as_p}}
    {{ image_form.as_p }}
    <button class="btn btn-success">등록하기</button>
  </form>
{% endblock %}

SWIDEA_SITE/ideas/templates/tool_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="tool_detail">
    <div><h2>개발툴 디테일</h2></div>
    
    <div class="tool_detail_content">
        <p>{{ tool.name }}</p>
        <p>{{ tool.kind }}</p>
        <p>{{ tool.context }}</p>
    </div>
    
    <ul>
        <p>만들 수 있는 SW 목록</p>
        {% for idea in ideas %}

            <li><a href="{% url 'ideas:idea_detail' pk=idea.id %}">{{ idea.title }}</a></li>
        {% endfor %}
    </ul>
    
    <div class="devtool_detail_btn">
        <form action="/devtools/{{tool.id}}/delete" method="post" class="delete-btn">
            {% csrf_token %}
            <input id="input6" type="submit" value="Delete">
        </form>
    
        <button>
            <a href="{% url 'ideas:tool_update' pk=tool.id %}" class="plus">
                <i class="ri-edit-2-line"></i>
                <p>Edit</p>
            </a>
        </button>
    
        <button>
            <a href="/devtools" class="plus">
                <i class="ri-edit-2-line"></i>
                <p>목록</p>
            </a>
        </button>
    </div>
</div>

{% endblock %}

SWIDEA_SITE/ideas/templates/tool_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h2>툴 리스트</h2>
  <div class="tool_list">
    {%for tool in tools%}
      <div class="tool_list_content">
        <p><a href="{{tool.id}}">{{ tool.name }}</a></p>
        <p>{{ tool.kind }}</p>
        <p>{{ tool.context }}</p>
      </div>
    {% endfor %}
  </div>
{% endblock %}

SWIDEA_SITE/ideas/templates/tool_update.html
{% extends 'base.html' %}

{% block content %}
<h2>개발툴 업데이트</h2>
<form
    action="{% url 'ideas:tool_update' pk=pk %}"
    method="post"
    enctype="multipart/form-data">
    {%csrf_token%} {{form.as_p}}
    <button class="btn btn-success">등록하기</button>
  </form>
{% endblock %}